name: CI - Backend Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: sparktrace.settings
      API_KEY: ${{ secrets.API_KEY }}  

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar tests con cobertura
      run: |
        pytest --tb=short --disable-warnings --cov=. --cov-report=xml --cov-report=term-missing

    - name: Subir cobertura a Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
        flags: unittests
        name: sparktrace-tests
        fail_ci_if_error: true
